
blank_issues_enabled: true
contact_links:
  - name: Discussion, Questions and chit-chat
    url: https://github.com/vintagepc/MK404/discussions
    about: Please use Discussions for questions, chat, and open-ended ideas.
