; generated by PrusaSlicer 2.3.0-alpha0 on 2020-10-02 at 23:23:38 UTC

; QUALITY

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.40mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.40mm

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.40mm

M73 P0 R7
M73 Q0 S7
M201 X1000 Y1000 Z1000 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm/sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107 ; disable fan
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.8.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode

M302 S0 ; cold extrusion

G92 E0.0 ; reset extrusion distance
G1 Y-3.0 F1000.0 ; go outside print area
G1 E2 F1000 ; de-retract and push ooze
M73 Q0 S7
M73 P0 R7
G1 X20.0 E6  F1000.0 ; fat 20mm intro line @ 0.30
G1 X60.0 E3.2  F1000.0 ; thin +40mm intro line @ 0.08
G1 X100.0 E6  F1000.0 ; fat +40mm intro line @ 0.15
G1 E-0.8 F2100; retract to avoid stringing
G1 X99.0 E0 F1000.0 ; -1mm intro line @ 0.00
G1 X110.0 E0 F1000.0 ; +10mm intro line @ 0.00
G1 E0.6 F1500; de-retract
G92 E0.0 ; reset extrusion distance
; Final print adjustments
M221 S95
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.09 ; Filament gcode"
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2
;LAYER:0
G1 E-0.40000 F4800.00000 ; retract
G1 Z0.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z0.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S1000 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
M106 S255 ; enable fan
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4
;LAYER:1
G1 E-0.40000 F4800.00000 ; retract
G1 Z0.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z0.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.6
;LAYER:2
G1 E-0.40000 F4800.00000 ; retract
G1 Z0.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z0.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.8
;LAYER:3
G1 E-0.40000 F4800.00000 ; retract
G1 Z0.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;0.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z0.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1
;LAYER:4
G1 E-0.40000 F4800.00000 ; retract
G1 Z1.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;1
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z1.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.2
;LAYER:5
G1 E-0.40000 F4800.00000 ; retract
G1 Z1.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z1.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.4
;LAYER:6
G1 E-0.40000 F4800.00000 ; retract
G1 Z1.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z1.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.6
;LAYER:7
G1 E-0.40000 F4800.00000 ; retract
G1 Z1.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z1.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;1.8
;LAYER:8
G1 E-0.40000 F4800.00000 ; retract
G1 Z1.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;1.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z1.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2
;LAYER:9
G1 E-0.40000 F4800.00000 ; retract
G1 Z2.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z2.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.2
;LAYER:10
G1 E-0.40000 F4800.00000 ; retract
G1 Z2.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;2.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z2.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.4
;LAYER:11
G1 E-0.40000 F4800.00000 ; retract
G1 Z2.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;2.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z2.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.6
;LAYER:12
G1 E-0.40000 F4800.00000 ; retract
G1 Z2.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;2.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z2.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;2.8
;LAYER:13
G1 E-0.40000 F4800.00000 ; retract
G1 Z2.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;2.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z2.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;3
;LAYER:14
G1 E-0.40000 F4800.00000 ; retract
G1 Z3.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;3
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z3.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;3.2
;LAYER:15
G1 E-0.40000 F4800.00000 ; retract
G1 Z3.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;3.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z3.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;3.4
;LAYER:16
G1 E-0.40000 F4800.00000 ; retract
M73 Q14 S6
G1 Z3.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;3.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z3.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 P15 R6
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;3.6
;LAYER:17
G1 E-0.40000 F4800.00000 ; retract
G1 Z3.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;3.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z3.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;3.8
;LAYER:18
G1 E-0.40000 F4800.00000 ; retract
G1 Z3.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;3.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z3.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;4
;LAYER:19
G1 E-0.40000 F4800.00000 ; retract
G1 Z4.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z4.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;4.2
;LAYER:20
G1 E-0.40000 F4800.00000 ; retract
G1 Z4.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;4.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z4.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;4.4
;LAYER:21
G1 E-0.40000 F4800.00000 ; retract
G1 Z4.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;4.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z4.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;4.6
;LAYER:22
G1 E-0.40000 F4800.00000 ; retract
G1 Z4.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;4.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z4.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;4.8
;LAYER:23
G1 E-0.40000 F4800.00000 ; retract
G1 Z4.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;4.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z4.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;5
;LAYER:24
G1 E-0.40000 F4800.00000 ; retract
G1 Z5.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;5
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z5.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;5.2
;LAYER:25
G1 E-0.40000 F4800.00000 ; retract
G1 Z5.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;5.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z5.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;5.4
;LAYER:26
G1 E-0.40000 F4800.00000 ; retract
G1 Z5.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;5.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z5.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;5.6
;LAYER:27
G1 E-0.40000 F4800.00000 ; retract
G1 Z5.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;5.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z5.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;5.8
;LAYER:28
G1 E-0.40000 F4800.00000 ; retract
G1 Z5.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;5.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z5.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;6
;LAYER:29
G1 E-0.40000 F4800.00000 ; retract
G1 Z6.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z6.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;6.2
;LAYER:30
G1 E-0.40000 F4800.00000 ; retract
G1 Z6.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;6.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z6.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;6.4
;LAYER:31
G1 E-0.40000 F4800.00000 ; retract
G1 Z6.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;6.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z6.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;6.6
;LAYER:32
G1 E-0.40000 F4800.00000 ; retract
G1 Z6.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;6.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z6.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;6.8
;LAYER:33
G1 E-0.40000 F4800.00000 ; retract
G1 Z6.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;6.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z6.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;7
;LAYER:34
G1 E-0.40000 F4800.00000 ; retract
G1 Z7.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;7
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z7.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 Q28 S5
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;7.2
;LAYER:35
G1 E-0.40000 F4800.00000 ; retract
G1 Z7.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;7.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z7.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 P29 R5
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;7.4
;LAYER:36
G1 E-0.40000 F4800.00000 ; retract
G1 Z7.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;7.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z7.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;7.6
;LAYER:37
G1 E-0.40000 F4800.00000 ; retract
G1 Z7.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;7.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z7.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;7.8
;LAYER:38
G1 E-0.40000 F4800.00000 ; retract
G1 Z7.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;7.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z7.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;8
;LAYER:39
G1 E-0.40000 F4800.00000 ; retract
G1 Z8.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z8.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;8.2
;LAYER:40
G1 E-0.40000 F4800.00000 ; retract
G1 Z8.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;8.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z8.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;8.4
;LAYER:41
G1 E-0.40000 F4800.00000 ; retract
G1 Z8.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;8.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z8.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;8.6
;LAYER:42
G1 E-0.40000 F4800.00000 ; retract
G1 Z8.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;8.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z8.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;8.8
;LAYER:43
G1 E-0.40000 F4800.00000 ; retract
G1 Z8.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;8.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z8.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;9
;LAYER:44
G1 E-0.40000 F4800.00000 ; retract
G1 Z9.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;9
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z9.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;9.2
;LAYER:45
G1 E-0.40000 F4800.00000 ; retract
G1 Z9.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;9.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z9.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;9.4
;LAYER:46
G1 E-0.40000 F4800.00000 ; retract
G1 Z9.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;9.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z9.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;9.6
;LAYER:47
G1 E-0.40000 F4800.00000 ; retract
G1 Z9.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;9.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z9.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;9.8
;LAYER:48
G1 E-0.40000 F4800.00000 ; retract
G1 Z9.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;9.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z9.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;10
;LAYER:49
G1 E-0.40000 F4800.00000 ; retract
G1 Z10.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;10
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z10.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;10.2
;LAYER:50
G1 E-0.40000 F4800.00000 ; retract
G1 Z10.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;10.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z10.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;10.4
;LAYER:51
G1 E-0.40000 F4800.00000 ; retract
G1 Z10.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;10.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z10.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;10.6
;LAYER:52
G1 E-0.40000 F4800.00000 ; retract
G1 Z10.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;10.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z10.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;10.8
;LAYER:53
G1 E-0.40000 F4800.00000 ; retract
G1 Z10.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;10.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z10.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 Q43 S4
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;11
;LAYER:54
G1 E-0.40000 F4800.00000 ; retract
G1 Z11.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;11
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z11.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 P44 R4
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;11.2
;LAYER:55
G1 E-0.40000 F4800.00000 ; retract
G1 Z11.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;11.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z11.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;11.4
;LAYER:56
G1 E-0.40000 F4800.00000 ; retract
G1 Z11.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;11.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z11.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;11.6
;LAYER:57
G1 E-0.40000 F4800.00000 ; retract
G1 Z11.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;11.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z11.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;11.8
;LAYER:58
G1 E-0.40000 F4800.00000 ; retract
G1 Z11.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;11.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z11.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;12
;LAYER:59
G1 E-0.40000 F4800.00000 ; retract
G1 Z12.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;12
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z12.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;12.2
;LAYER:60
G1 E-0.40000 F4800.00000 ; retract
G1 Z12.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;12.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z12.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;12.4
;LAYER:61
G1 E-0.40000 F4800.00000 ; retract
G1 Z12.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;12.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z12.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;12.6
;LAYER:62
G1 E-0.40000 F4800.00000 ; retract
G1 Z12.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;12.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z12.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;12.8
;LAYER:63
G1 E-0.40000 F4800.00000 ; retract
G1 Z12.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;12.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z12.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;13
;LAYER:64
G1 E-0.40000 F4800.00000 ; retract
G1 Z13.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;13
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z13.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;13.2
;LAYER:65
G1 E-0.40000 F4800.00000 ; retract
G1 Z13.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;13.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z13.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;13.4
;LAYER:66
G1 E-0.40000 F4800.00000 ; retract
G1 Z13.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;13.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z13.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;13.6
;LAYER:67
G1 E-0.40000 F4800.00000 ; retract
G1 Z13.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;13.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z13.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;13.8
;LAYER:68
G1 E-0.40000 F4800.00000 ; retract
G1 Z13.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;13.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z13.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;14
;LAYER:69
G1 E-0.40000 F4800.00000 ; retract
G1 Z14.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;14
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z14.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;14.2
;LAYER:70
G1 E-0.40000 F4800.00000 ; retract
G1 Z14.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;14.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z14.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;14.4
;LAYER:71
G1 E-0.40000 F4800.00000 ; retract
G1 Z14.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;14.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z14.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;14.6
;LAYER:72
G1 E-0.40000 F4800.00000 ; retract
G1 Z14.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;14.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z14.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 Q58 S3
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;14.8
;LAYER:73
G1 E-0.40000 F4800.00000 ; retract
G1 Z14.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;14.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z14.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 P59 R3
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;15
;LAYER:74
G1 E-0.40000 F4800.00000 ; retract
G1 Z15.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;15
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z15.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;15.2
;LAYER:75
G1 E-0.40000 F4800.00000 ; retract
G1 Z15.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;15.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z15.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;15.4
;LAYER:76
G1 E-0.40000 F4800.00000 ; retract
G1 Z15.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;15.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z15.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;15.6
;LAYER:77
G1 E-0.40000 F4800.00000 ; retract
G1 Z15.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;15.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z15.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;15.8
;LAYER:78
G1 E-0.40000 F4800.00000 ; retract
G1 Z15.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;15.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z15.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;16
;LAYER:79
G1 E-0.40000 F4800.00000 ; retract
G1 Z16.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;16
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z16.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;16.2
;LAYER:80
G1 E-0.40000 F4800.00000 ; retract
G1 Z16.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;16.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z16.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;16.4
;LAYER:81
G1 E-0.40000 F4800.00000 ; retract
G1 Z16.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;16.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z16.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;16.6
;LAYER:82
G1 E-0.40000 F4800.00000 ; retract
G1 Z16.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;16.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z16.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;16.8
;LAYER:83
G1 E-0.40000 F4800.00000 ; retract
G1 Z16.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;16.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z16.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;17
;LAYER:84
G1 E-0.40000 F4800.00000 ; retract
G1 Z17.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;17
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z17.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;17.2
;LAYER:85
G1 E-0.40000 F4800.00000 ; retract
G1 Z17.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;17.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z17.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;17.4
;LAYER:86
G1 E-0.40000 F4800.00000 ; retract
G1 Z17.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;17.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z17.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;17.6
;LAYER:87
G1 E-0.40000 F4800.00000 ; retract
G1 Z17.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;17.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z17.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;17.8
;LAYER:88
G1 E-0.40000 F4800.00000 ; retract
G1 Z17.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;17.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z17.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;18
;LAYER:89
G1 E-0.40000 F4800.00000 ; retract
G1 Z18.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;18
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z18.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;18.2
;LAYER:90
G1 E-0.40000 F4800.00000 ; retract
G1 Z18.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;18.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z18.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;18.4
;LAYER:91
G1 E-0.40000 F4800.00000 ; retract
G1 Z18.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;18.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z18.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 Q73 S2
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;18.6
;LAYER:92
G1 E-0.40000 F4800.00000 ; retract
G1 Z18.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;18.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z18.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 P73 R2
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;18.8
;LAYER:93
G1 E-0.40000 F4800.00000 ; retract
G1 Z18.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;18.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z18.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;19
;LAYER:94
G1 E-0.40000 F4800.00000 ; retract
G1 Z19.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;19
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z19.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;19.2
;LAYER:95
G1 E-0.40000 F4800.00000 ; retract
G1 Z19.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;19.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z19.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;19.4
;LAYER:96
G1 E-0.40000 F4800.00000 ; retract
G1 Z19.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;19.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z19.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;19.6
;LAYER:97
G1 E-0.40000 F4800.00000 ; retract
G1 Z19.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;19.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z19.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;19.8
;LAYER:98
G1 E-0.40000 F4800.00000 ; retract
G1 Z19.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;19.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z19.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;20
;LAYER:99
G1 E-0.40000 F4800.00000 ; retract
G1 Z20.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;20
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z20.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;20.2
;LAYER:100
G1 E-0.40000 F4800.00000 ; retract
G1 Z20.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;20.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z20.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;20.4
;LAYER:101
G1 E-0.40000 F4800.00000 ; retract
G1 Z20.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;20.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z20.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;20.6
;LAYER:102
G1 E-0.40000 F4800.00000 ; retract
G1 Z20.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;20.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z20.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;20.8
;LAYER:103
G1 E-0.40000 F4800.00000 ; retract
G1 Z20.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;20.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z20.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;21
;LAYER:104
G1 E-0.40000 F4800.00000 ; retract
G1 Z21.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;21
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z21.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;21.2
;LAYER:105
G1 E-0.40000 F4800.00000 ; retract
G1 Z21.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;21.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z21.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;21.4
;LAYER:106
G1 E-0.40000 F4800.00000 ; retract
G1 Z21.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;21.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z21.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;21.6
;LAYER:107
G1 E-0.40000 F4800.00000 ; retract
G1 Z21.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;21.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z21.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;21.8
;LAYER:108
G1 E-0.40000 F4800.00000 ; retract
G1 Z21.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;21.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z21.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;22
;LAYER:109
G1 E-0.40000 F4800.00000 ; retract
G1 Z22.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;22
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z22.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;22.2
;LAYER:110
G1 E-0.40000 F4800.00000 ; retract
G1 Z22.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;22.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z22.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 Q87 S1
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;22.4
;LAYER:111
G1 E-0.40000 F4800.00000 ; retract
G1 Z22.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;22.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z22.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M73 P88 R1
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;22.6
;LAYER:112
G1 E-0.40000 F4800.00000 ; retract
G1 Z22.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;22.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z22.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;22.8
;LAYER:113
G1 E-0.40000 F4800.00000 ; retract
G1 Z22.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;22.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z22.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;23
;LAYER:114
G1 E-0.40000 F4800.00000 ; retract
G1 Z23.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;23
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z23.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;23.2
;LAYER:115
G1 E-0.40000 F4800.00000 ; retract
G1 Z23.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;23.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z23.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;23.4
;LAYER:116
G1 E-0.40000 F4800.00000 ; retract
G1 Z23.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;23.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z23.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;23.6
;LAYER:117
G1 E-0.40000 F4800.00000 ; retract
G1 Z23.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;23.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z23.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;23.8
;LAYER:118
G1 E-0.40000 F4800.00000 ; retract
G1 Z23.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;23.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z23.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;24
;LAYER:119
G1 E-0.40000 F4800.00000 ; retract
G1 Z24.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;24
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z24.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;24.2
;LAYER:120
G1 E-0.40000 F4800.00000 ; retract
G1 Z24.300 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;24.2
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z24.200 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;24.4
;LAYER:121
G1 E-0.40000 F4800.00000 ; retract
G1 Z24.500 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;24.4
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z24.400 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;24.6
;LAYER:122
G1 E-0.40000 F4800.00000 ; retract
G1 Z24.700 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;24.6
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z24.600 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;24.8
;LAYER:123
G1 E-0.40000 F4800.00000 ; retract
G1 Z24.900 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;24.8
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z24.800 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
;BEFORE_LAYER_CHANGE
G92 E0.0
;25
;LAYER:124
G1 E-0.40000 F4800.00000 ; retract
G1 Z25.100 F12000.000 ; lift Z
;AFTER_LAYER_CHANGE
;25
; printing object Shape-Box id:0 copy 0
G1 X105.000 Y105.000 ; move to first perimeter point
G1 Z25.000 ; restore layer Z
G1 E0.40000 F1500.00000 ; unretract
M204 S800 ; adjust acceleration
G1 F900
G1 X145.000 Y105.000 E1.68218 ; perimeter
M204 S1250 ; adjust acceleration
; stop printing object Shape-Box id:0 copy 0
G1 E-0.40000 F4800.00000 ; retract
G1 Z25.300 F12000.000 ; lift Z
M107 ; disable fan
; Filament-specific end gcode
; Last updated 201811109
G4 ; wait
G92 E0 ; prepare to retract
G1 E-1 F2100; retract to avoid ooze
M221 S100 ; reset extruder factor to 100%
M900 K0 ; reset linear acceleration
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z85.3 ; Move print head up
G0 X0 Y200 ; present bed
M84 ; disable motors
M300 S100 P10 ; chirp
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 210.3
; filament used [cm3] = 0.5
; filament used [g] = 0.6
; filament cost = 0.0

; total filament used [g] = 0.6
; total filament cost = 0.0
; estimated printing time (normal mode) = 6m 49s
; estimated printing time (silent mode) = 7m 3s

; avoid_crossing_perimeters = 1
; bed_custom_model =
; bed_custom_texture =
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n;LAYER:[layer_num]
; between_objects_gcode =
; bottom_fill_pattern = monotonous
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]>=.25";
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 4000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 25
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = ; Last updated 201811109\nG4 ; wait\nG92 E0 ; prepare to retract\nG1 E-1 F2100; retract to avoid ooze\nM221 S100 ; reset extruder factor to 100%\nM900 K0 ; reset linear acceleration\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if layer_z < max_print_height}G1 Z{z_offset+min(layer_z+60, max_print_height)}{endif} ; Move print head up\nG0 X0 Y200 ; present bed\nM84 ; disable motors\nM300 S100 P10 ; chirp
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 50
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FFA200
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 15.99
; filament_density = 1.24
; filament_diameter = 1.74
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 5
; filament_notes = "List of materials tested with standart PLA print settings for MK2:\n\nDas Filament\nEsun PLA\nEUMAKERS PLA\nFiberlogy HD-PLA\nFillamentum PLA\nFloreon3D\nHatchbox PLA\nPlasty Mladeč PLA\nPrimavalue PLA\nProto pasta Matte Fiber\nVerbatim PLA\nVerbatim BVOH\n\nLA, extrusion rate & diameter calibrated 20181005"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "GeeeTech PLa"
; filament_soluble = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = 3D Solutech
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0
; first_layer_height = 0.2
; first_layer_speed = 30
; first_layer_temperature = 205
; gap_fill_speed = 40
; gcode_comments = 1
; gcode_flavor = marlin
; gcode_label_objects = 1
; high_current_on_filament_swap = 0
; host_type = flashair
; infill_acceleration = 1500
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 200
; inherits_cummulative = ;;"Original Prusa i3 MK3S"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 1000,1000
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.3
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_speed = 11.5
; min_fan_speed = 75
; min_layer_height = 0.1
; min_print_speed = 15
; min_skirt_length = 4
; notes = QUALITY
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base] [filament_type] [print_time].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 60
; perimeters = 3
; post_process =
; print_settings_id = S 0.20mm layers for 0.25mm+ nozzle
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S Skelestruder
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor =
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.4
; retract_length_toolchange = 4
; retract_lift = 0.3
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 80
; seam_position = aligned
; serial_port =
; serial_speed = 250000
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 3
; skirt_height = 2
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 20
; small_perimeter_speed = 35
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 200
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}0.09{endif} ; Filament gcode\""
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.8.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S[first_layer_bed_temperature] ; set bed temp\nM104 S160 ; set extruder no-ooze temp\nM190 ; wait for bed\nM109 ; wait for extruder\n\nG28 W ; home all without mesh bed level\nM914 ; High power MBL\nG80 ; mesh bed leveling\nM914 R ; Stealth print\n\nM104 S[first_layer_temperature] ; set extruder temp\nM109 S[first_layer_temperature] ; wait for extruder temp\n\nM907 E400; Set extruder current limit for pancake\n\nG92 E0.0 ; reset extrusion distance\nG1 Y-3.0 F1000.0 ; go outside print area\nG1 E2 F1000 ; de-retract and push ooze\nG1 X20.0 E6  F1000.0 ; fat 20mm intro line @ 0.30\nG1 X60.0 E3.2  F1000.0 ; thin +40mm intro line @ 0.08\nG1 X100.0 E6  F1000.0 ; fat +40mm intro line @ 0.15\nG1 E-0.8 F2100; retract to avoid stringing\nG1 X99.0 E0 F1000.0 ; -1mm intro line @ 0.00\nG1 X110.0 E0 F1000.0 ; +10mm intro line @ 0.00\nG1 E0.6 F1500; de-retract\nG92 E0.0 ; reset extrusion distance\n; Final print adjustments\nM221 S{if layer_height==0.05}100{else}95{endif}
; support_material = 1
; support_material_angle = 0
; support_material_auto = 0
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_synchronize_layers = 0
; support_material_threshold = 45
; support_material_with_sheath = 0
; support_material_xy_spacing = 75%
; temperature = 205
; template_custom_gcode =
; thin_walls = 1
; threads = 8
; thumbnails =
; toolchange_gcode =
; top_fill_pattern = monotonous
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 35
; top_solid_layers = 4
; top_solid_min_thickness = 0
; travel_speed = 200
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 0
; wipe_tower_x = 0
; wipe_tower_y = 0
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
