# This is a basic workflow to help you get started with Actions

name: IWYU

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  iwyu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout ${{ github.event.pull_request.head.ref }}
      uses: actions/checkout@v2.2.0
      if: ${{ github.event.pull_request }}
      with:
        repository: vintagepc/MK404.git
        ref: ${{ github.event.pull_request.head.sha }}
        submodules: true

    - name: Checkout ${{ github.event.ref }}
      uses: actions/checkout@v2.2.0
      if: ${{ !github.event.pull_request }}
      with:
        repository: vintagepc/MK404.git
        ref: ${{ github.event.ref }}
        submodules: true

    - name: Cache packages
      uses: actions/cache@v1.0.3
      id: cache-pkgs
      with:
          path: "packages"
          key: "pkgs-1_0_5-iwyu"
    - name: Setup cache dir
      if:  ${{ ! steps.cache-valgrind.outputs.cache-hit }}
      run: mkdir -p packages/partial

    - name: Install packages
      run: |
        sudo apt-get update 
        sudo apt-get purge clang-*
        sudo apt-get -o Dir::Cache::Archives=`pwd`/packages install clang-5.0
        sudo apt-get -o Dir::Cache::Archives=`pwd`/packages install libelf-dev gcc-avr libglew-dev freeglut3-dev libsdl-sound1.2-dev iwyu
    - name: Cache permissions
      run: sudo chmod -R 744 packages

    - name: Prepare CMake build
      run: mkdir ${{ runner.workspace }}/MK404/build && cd ${{ runner.workspace }}/MK404/build && cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 -DENABLE_IWYU=1 ..

    - name: Run IWYU
      continue-on-error: true
      run: |
          cd ${{ runner.workspace }}/MK404/build && make |& tee IWYU.txt
          ! grep -q "include-what-you-use reported diagnostics" IWYU.txt
          
    - name: Upload IWYU log
      uses: actions/upload-artifact@v2
      with:
        name: IWYU
        path: ${{ runner.workspace }}/MK404/build/IWYU.txt
