# This is a basic workflow to help you get started with Actions

name: Code formatting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  formatting:
  - name: clang-tidy check
    uses: muxee/clang-tidy-action@0.0.1-rc1
