name: Build tagged release

on:
  push:
    tags:
      - "v*"

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Checkout ${{ steps.get_version.outputs.VERSION }} (${{ github.event.ref }})
      uses: actions/checkout@v2.2.0
      if: ${{ github.event.pull_request }}
      with:
        repository: vintagepc/MK3SIM.git
        ref: ${{ github.event.ref }}
        submodules: true
        
    - name: Cache packages
      uses: actions/cache@v1.0.3
      id: cache-pkgs
      with:
          path: "packages"
          key: ${{secrets.build_pkg_cache}}

    - name: Setup cache dir
      if:  ${{ ! steps.cache-valgrind.outputs.cache-hit }}
      run: mkdir -p packages/partial

    - name: Install packages
      run: sudo apt-get -o Dir::Cache::Archives=`pwd`/packages install libelf-dev gcc-avr libglew-dev freeglut3-dev libsdl-sound1.2-dev

    - name: Cache permissions
      run: sudo chmod -R 744 packages

    - name: Prepare CMake build
      run: mkdir ${{ runner.workspace }}/MK3SIM/build && cd ${{ runner.workspace }}/MK3SIM/build && cmake -DCMAKE_BUILD_TYPE=RELEASE ..

    - name: Build Einsy
      run: cd ${{ runner.workspace }}/MK3SIM/build && make
        
    - name: Assemble artifacts
      run: |
          cd ${{ runner.workspace }}/MK3SIM/build
          make Release_Package
          mv MK404-development-build.tar.bz2 MK404-${{ steps.get_version.outputs.VERSION }}.tar.bz2
    
    - name: Publish release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ runner.workspace }}/MK3SIM/build/MK404-${{ steps.get_version.outputs.VERSION }}.tar.bz2
